INSERT INTO users (
    user_id,
    username,
    email,
    email_verified_at,
    telegram_id,
    first_name,
    last_name,
    language_code,
    is_banned,
    panel_user_uuid,
    referral_code,
    telegram_notifications_status,
    channel_subscription_verified
) VALUES
    (
        910000001,
        'runes_admin',
        'runes.admin@example.com',
        now(),
        910000001,
        'Runes',
        'Admin',
        'ru',
        false,
        '00000000-0000-4000-8000-000000000001',
        'RUNESADMIN',
        'enabled',
        true
    ),
    (
        910000002,
        'runes_active',
        'runes.active@example.com',
        now(),
        910000002,
        'Runes',
        'Active',
        'ru',
        false,
        '00000000-0000-4000-8000-000000000002',
        'RUNESACTIVE',
        'unknown',
        true
    ),
    (
        910000003,
        'runes_expired',
        'runes.expired@example.com',
        now() - interval '45 days',
        910000003,
        'Runes',
        'Expired',
        'en',
        false,
        '00000000-0000-4000-8000-000000000003',
        'RUNESEXPIRED',
        'blocked',
        false
    )
ON CONFLICT (user_id) DO UPDATE SET
    username = EXCLUDED.username,
    email = EXCLUDED.email,
    email_verified_at = EXCLUDED.email_verified_at,
    telegram_id = EXCLUDED.telegram_id,
    first_name = EXCLUDED.first_name,
    last_name = EXCLUDED.last_name,
    language_code = EXCLUDED.language_code,
    is_banned = EXCLUDED.is_banned,
    panel_user_uuid = EXCLUDED.panel_user_uuid,
    referral_code = EXCLUDED.referral_code,
    telegram_notifications_status = EXCLUDED.telegram_notifications_status,
    channel_subscription_verified = EXCLUDED.channel_subscription_verified;

INSERT INTO subscriptions (
    user_id,
    panel_user_uuid,
    panel_subscription_uuid,
    install_share_token,
    start_date,
    end_date,
    duration_months,
    is_active,
    status_from_panel,
    traffic_limit_bytes,
    traffic_used_bytes,
    provider,
    skip_notifications,
    suppress_early_expiry_notifications,
    auto_renew_enabled,
    auto_renew_consent_version,
    tariff_key,
    tier_baseline_bytes,
    topup_balance_bytes,
    premium_baseline_bytes,
    premium_topup_balance_bytes,
    premium_topup_used_bytes,
    premium_used_bytes,
    premium_is_limited,
    premium_unlimited_override,
    premium_bonus_bytes,
    regular_bonus_bytes,
    regular_unlimited_override,
    period_start_at,
    is_throttled,
    effective_monthly_price_rub,
    hwid_device_limit,
    extra_hwid_devices
) VALUES
    (
        910000001,
        '00000000-0000-4000-8000-000000000001',
        '10000000-0000-4000-8000-000000000001',
        'devsharetokenadmin000001',
        now() - interval '10 days',
        now() + interval '20 days',
        1,
        true,
        'ACTIVE',
        107374182400,
        21474836480,
        'dev_seed',
        false,
        false,
        true,
        1,
        'standard',
        107374182400,
        10737418240,
        21474836480,
        5368709120,
        1073741824,
        2147483648,
        true,
        false,
        0,
        0,
        false,
        now() - interval '10 days',
        false,
        299.00,
        3,
        1
    ),
    (
        910000002,
        '00000000-0000-4000-8000-000000000002',
        '10000000-0000-4000-8000-000000000002',
        'devsharetokenactive00001',
        now() - interval '5 days',
        now() + interval '55 days',
        2,
        true,
        'LIMITED',
        214748364800,
        193273528320,
        'dev_seed',
        false,
        false,
        false,
        0,
        'premium',
        214748364800,
        0,
        107374182400,
        0,
        0,
        85899345920,
        true,
        false,
        10737418240,
        5368709120,
        false,
        now() - interval '5 days',
        true,
        499.00,
        5,
        0
    ),
    (
        910000003,
        '00000000-0000-4000-8000-000000000003',
        '10000000-0000-4000-8000-000000000003',
        'devsharetokenexpired0001',
        now() - interval '75 days',
        now() - interval '15 days',
        1,
        false,
        'EXPIRED',
        53687091200,
        53687091200,
        'dev_seed',
        true,
        true,
        false,
        0,
        'standard',
        53687091200,
        0,
        0,
        0,
        0,
        0,
        false,
        false,
        0,
        0,
        false,
        now() - interval '75 days',
        false,
        299.00,
        1,
        0
    )
ON CONFLICT (panel_subscription_uuid) DO UPDATE SET
    user_id = EXCLUDED.user_id,
    panel_user_uuid = EXCLUDED.panel_user_uuid,
    install_share_token = EXCLUDED.install_share_token,
    start_date = EXCLUDED.start_date,
    end_date = EXCLUDED.end_date,
    duration_months = EXCLUDED.duration_months,
    is_active = EXCLUDED.is_active,
    status_from_panel = EXCLUDED.status_from_panel,
    traffic_limit_bytes = EXCLUDED.traffic_limit_bytes,
    traffic_used_bytes = EXCLUDED.traffic_used_bytes,
    provider = EXCLUDED.provider,
    skip_notifications = EXCLUDED.skip_notifications,
    suppress_early_expiry_notifications = EXCLUDED.suppress_early_expiry_notifications,
    auto_renew_enabled = EXCLUDED.auto_renew_enabled,
    auto_renew_consent_version = EXCLUDED.auto_renew_consent_version,
    tariff_key = EXCLUDED.tariff_key,
    tier_baseline_bytes = EXCLUDED.tier_baseline_bytes,
    topup_balance_bytes = EXCLUDED.topup_balance_bytes,
    premium_baseline_bytes = EXCLUDED.premium_baseline_bytes,
    premium_topup_balance_bytes = EXCLUDED.premium_topup_balance_bytes,
    premium_topup_used_bytes = EXCLUDED.premium_topup_used_bytes,
    premium_used_bytes = EXCLUDED.premium_used_bytes,
    premium_is_limited = EXCLUDED.premium_is_limited,
    premium_unlimited_override = EXCLUDED.premium_unlimited_override,
    premium_bonus_bytes = EXCLUDED.premium_bonus_bytes,
    regular_bonus_bytes = EXCLUDED.regular_bonus_bytes,
    regular_unlimited_override = EXCLUDED.regular_unlimited_override,
    period_start_at = EXCLUDED.period_start_at,
    is_throttled = EXCLUDED.is_throttled,
    effective_monthly_price_rub = EXCLUDED.effective_monthly_price_rub,
    hwid_device_limit = EXCLUDED.hwid_device_limit,
    extra_hwid_devices = EXCLUDED.extra_hwid_devices;

INSERT INTO payments (
    user_id,
    provider_payment_id,
    provider_payment_url,
    provider,
    idempotence_key,
    amount,
    currency,
    status,
    description,
    subscription_duration_months,
    is_auto_renew,
    sale_mode,
    tariff_key,
    purchased_gb,
    purchased_hwid_devices,
    created_at,
    updated_at
) VALUES
    (
        910000001,
        'dev-payment-runes-admin-001',
        'https://payments.example.test/dev-payment-runes-admin-001',
        'dev_seed',
        'dev-idempotence-runes-admin-001',
        299.00,
        'RUB',
        'succeeded',
        'Dev seed subscription payment',
        1,
        false,
        'subscription@standard',
        'standard',
        null,
        null,
        now() - interval '10 days',
        now() - interval '10 days'
    ),
    (
        910000002,
        'dev-payment-runes-active-001',
        'https://payments.example.test/dev-payment-runes-active-001',
        'dev_seed',
        'dev-idempotence-runes-active-001',
        499.00,
        'RUB',
        'succeeded',
        'Dev seed premium subscription payment',
        2,
        false,
        'subscription@premium',
        'premium',
        null,
        null,
        now() - interval '5 days',
        now() - interval '5 days'
    ),
    (
        910000002,
        'dev-payment-runes-active-topup-001',
        'https://payments.example.test/dev-payment-runes-active-topup-001',
        'dev_seed',
        'dev-idempotence-runes-active-topup-001',
        149.00,
        'RUB',
        'pending',
        'Dev seed traffic top-up payment',
        null,
        false,
        'topup@premium',
        'premium',
        10,
        null,
        now() - interval '1 day',
        now() - interval '1 day'
    )
ON CONFLICT (provider, provider_payment_id) DO UPDATE SET
    user_id = EXCLUDED.user_id,
    provider_payment_url = EXCLUDED.provider_payment_url,
    provider = EXCLUDED.provider,
    idempotence_key = EXCLUDED.idempotence_key,
    amount = EXCLUDED.amount,
    currency = EXCLUDED.currency,
    status = EXCLUDED.status,
    description = EXCLUDED.description,
    subscription_duration_months = EXCLUDED.subscription_duration_months,
    is_auto_renew = EXCLUDED.is_auto_renew,
    sale_mode = EXCLUDED.sale_mode,
    tariff_key = EXCLUDED.tariff_key,
    purchased_gb = EXCLUDED.purchased_gb,
    purchased_hwid_devices = EXCLUDED.purchased_hwid_devices,
    updated_at = now();
