"""Generate the human Remnawave compatibility catalog from runtime contracts."""

from __future__ import annotations

import argparse
from pathlib import Path

from bot.services.panel_api_contracts import (
    PANEL_API_OPERATION_CONTRACTS,
    PANEL_WEBHOOK_CONTRACTS,
    load_support_manifest,
)

REPO_ROOT = Path(__file__).resolve().parents[3]
DEFAULT_OUTPUT_PATH = REPO_ROOT / "docs" / "architecture" / "remnawave-api-compatibility.md"


def _cell(value: object) -> str:
    return str(value).replace("|", "\\|").replace("\n", " ")


def _generation_names(values: object) -> str:
    if not isinstance(values, (list, tuple)):
        return "—"
    return ", ".join(str(getattr(value, "value", value)) for value in values) or "—"


def generate_remnawave_api_markdown() -> str:
    manifest = load_support_manifest()
    policy = manifest["policy"]
    generations = manifest["generations"]
    historical = manifest["historical_versions"]
    upgrades = manifest["upgrade_paths"]

    lines = [
        "# Remnawave API compatibility",
        "",
        "<!-- Generated by `PYTHONPATH=backend python -m bot.services.panel_api_catalog`. -->",
        "",
        "This catalog is generated from the same typed registry used by the runtime client. ",
        "Do not edit it manually: update `panel_api_contracts.py` or ",
        "`remnawave_support.json`, regenerate, and run the contract tests.",
        "",
        "## Support policy",
        "",
        f"Core certifies {policy['supported_api_generations']} API generations at a time: the ",
        "current generation and one maintenance generation. Exact versions are certified; a new ",
        "patch/minor in a known generation is reported as **unverified** until live CI is green. ",
        f"Removal gets at least {policy['deprecation_minimum_days']} days and ",
        f"{policy['deprecation_minimum_core_releases']} Core releases of notice, and requires a ",
        "breaking Core release.",
        "",
        "Unknown future Remnawave major versions run in best-effort mode: existing reads and",
        "writes remain available because a major bump does not necessarily change the API. They",
        "stay marked unverified until certified, and endpoint/capability fallbacks limit",
        "assumptions. If the metadata endpoint is temporarily unavailable, Core preserves",
        "best-effort compatibility and",
        "uses identifier/endpoint observations instead of caching a false version result.",
        "",
        "## Certified versions",
        "",
        (
            "| Status | API generation | Exact versions | Preset | Capabilities | Coverage | "
            "Upstream |"
        ),
        "| --- | --- | --- | --- | --- | --- | --- |",
    ]
    for item in generations:
        upstream = str(item["upstream_release"])
        lines.append(
            "| "
            + " | ".join(
                (
                    _cell(item["status"]),
                    _cell(item["id"]),
                    _cell(", ".join(item["certified_versions"])),
                    _cell(item["preset"]),
                    _cell(", ".join(item["capabilities"]) or "—"),
                    _cell(", ".join(item["coverage"])),
                    f"[release notes]({upstream})",
                )
            )
            + " |"
        )

    lines.extend(
        [
            "",
            "Historical presets remain useful for manual investigations but are not supported or ",
            "run in the certification matrix:",
            "",
        ]
    )
    lines.extend(f"- `{item['version']}` — {item['reason']}" for item in historical)

    lines.extend(
        [
            "",
            "## Outbound API operations",
            "",
            "`{userRef}` is a user UUID in 2.8.1 and the decimal form of a numeric user id in ",
            "3.0.0. Other UUIDs (nodes, squads, hosts, subscriptions) remain UUIDs.",
            "",
            (
                "| Operation | Method | Path template | Generations | Success | Response | "
                "Compatibility | Coverage |"
            ),
            "| --- | --- | --- | --- | --- | --- | --- | --- |",
        ]
    )
    for contract in PANEL_API_OPERATION_CONTRACTS:
        response = contract.response_shape
        if contract.empty_success_body:
            response += "; an empty 2xx body is success"
        lines.append(
            "| "
            + " | ".join(
                (
                    f"`{contract.operation.value}`",
                    contract.method,
                    f"`{_cell(contract.path)}`",
                    _generation_names(contract.generations),
                    ", ".join(str(value) for value in contract.success_statuses),
                    _cell(response),
                    _cell(contract.compatibility_note),
                    _generation_names(contract.coverage),
                )
            )
            + " |"
        )

    lines.extend(
        [
            "",
            "## Inbound webhooks",
            "",
            "| Event | Generations | Identity handling | Core behavior | Coverage |",
            "| --- | --- | --- | --- | --- |",
        ]
    )
    lines.extend(
        (
            "| "
            + " | ".join(
                (
                    _cell(contract.event),
                    _generation_names(contract.generations),
                    _cell(contract.identity),
                    _cell(contract.behavior),
                    _generation_names(contract.coverage),
                )
            )
            + " |"
        )
        for contract in PANEL_WEBHOOK_CONTRACTS
    )

    lines.extend(
        [
            "",
            "## Certified upgrades",
            "",
            "| From | To | Strategy | Verification |",
            "| --- | --- | --- | --- |",
        ]
    )
    lines.extend(
        (f"| {item['from']} | {item['to']} | {item['strategy']} | `{item['verification']}` |")
        for item in upgrades
    )

    lines.extend(
        [
            "",
            "## Compatibility rules and corner cases",
            "",
            "- Panel version detection has a five-minute positive cache. Failures are not cached, ",
            "  so startup races and temporary authorization failures self-heal.",
            "- 3.x users are normalized at the boundary: numeric `id` is also exposed",
            "  internally as a decimal-string `uuid` alias. This intentionally preserves",
            "  historical DB columns and",
            "  service method names during an in-place panel upgrade.",
            "- Once the generation is known, user-scoped requests reject an identifier from",
            "  the other generation locally. This prevents 3.x validation-error storms and",
            "  prevents a stale UUID from being mistaken for a deleted user.",
            "- Background tariff synchronization lazily relinks stale 2.8 UUIDs through",
            "  Telegram/email/deterministic username identity before it can deactivate a",
            "  subscription. Failed or ambiguous identity lookups never create a duplicate user.",
            "- 2.8.1 uses offset `/users` pagination and UUID lookup routes. 3.x uses",
            "  the cursor stream and stream filters. Responses are shape-checked before a",
            "  capability is learned.",
            "- User-miss responses A025, A062, A063, and plain 404 are normalized as an",
            "  empty lookup result. Removed-route 404 responses are handled first so a live",
            "  2.8-to-3.x upgrade switches to stream filters without restarting Mini Shop.",
            "- Empty 202/204 responses are accepted for mutation operations documented that way; ",
            "  malformed non-empty 2xx JSON is still a protocol error.",
            "- The 2.8.1 squad `add-users` route means all users. Core never calls it for",
            "  a targeted request; it patches each requested UUID user. 3.x uses chunked",
            "  numeric-id bulk calls.",
            "- Logs use registry labels instead of raw paths, preventing identifiers in",
            "  route segments",
            "  and query strings from becoming log/metric labels.",
            "",
            "## New Remnawave release checklist",
            "",
            "1. Read the upstream release/API diff and classify the API generation. Future majors ",
            "   remain best-effort compatible, but are never presented as certified without",
            "   live QA.",
            "2. Add or update an exact entry in `remnawave_support.json` and a dev-stand",
            "   preset. Keep",
            "   historical presets clearly separate from the certified matrix.",
            "3. Update every affected operation contract, compatibility adapter, webhook",
            "   normalizer,",
            "   version fixture, and all certified-version live jobs.",
            "4. Run read/write smoke tests for current and maintenance versions. For",
            "   generation changes, also run the same-database upgrade job and verify persisted",
            "   user identities after sync.",
            "5. Regenerate this catalog and public API artifacts, then run all",
            "   backend/frontend gates.",
            "6. To retire a generation, announce deprecation for the policy window, remove",
            "   it only in a",
            "   breaking Core release, and move its presets to historical status.",
            "",
            f"Manifest review date: `{manifest['reviewed_at']}`.",
            "",
        ]
    )
    return "\n".join(line.rstrip() for line in lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if the generated file drifts")
    args = parser.parse_args()
    generated = generate_remnawave_api_markdown()
    if args.check:
        actual = DEFAULT_OUTPUT_PATH.read_text(encoding="utf-8")
        if actual != generated:
            raise SystemExit(f"{DEFAULT_OUTPUT_PATH} is stale; regenerate the catalog")
        return
    DEFAULT_OUTPUT_PATH.write_text(generated, encoding="utf-8")


if __name__ == "__main__":
    main()
