import { DEFAULT_DISPOSABLE_EMAIL_DOMAINS } from "./disposableEmailDomains";
import { INSTALL_GUIDES_CONFIG } from "./installGuidesConfig";
import { ASCII_THEME, DEFAULT_DARK_THEME, LEGACY_LIGHT_THEME, WINDOWS_95_THEME } from "./themes";
import type { PreviewMock } from "./types";

export const DEV_MOCK: PreviewMock = {
  config: {
    title: "/minishop",
    primaryColor: "#00fe7a",
    logoUrl: "/webapp-default-logo.webp",
    faviconUrl: "/webapp-favicon/19b2a242e5b7bc2d/icon-180.png",
    faviconUseCustom: false,
    trialEnabled: true,
    trialDurationDays: 3,
    trialTrafficLimitGb: 5,
    trialHwidDeviceLimit: 1,
    trialTrafficStrategy: "NO_RESET",
    trialWithoutTelegramEnabled: true,
    trialSquadUuids: "2f2f6e0a-1f2d-4e80-a33b-0ebf3a409012",
    referralWelcomeBonusDays: 3,
    referralWelcomeWithoutTelegramEnabled: true,
    referralOneBonusPerReferee: false,
    legacyRefs: true,
    disposableEmailDomains: DEFAULT_DISPOSABLE_EMAIL_DOMAINS,
    apiBase: "/api",
    adminJsAsset: "subscription_webapp_admin.js",
    adminCssAsset: "subscription_webapp_admin.css",
    supportUrl: "https://t.me/support",
    serverStatusUrl: "https://status.example.com",
    privacyPolicyUrl: "https://example.com/privacy",
    userAgreementUrl: "https://example.com/agreement",
    currency: "RUB",
    language: "ru",
    languages: [
      { code: "ru", label: "Русский", flag: "🇷🇺", base: true },
      { code: "en", label: "English", flag: "🇬🇧", base: true },
    ],
    emailAuthEnabled: true,
    telegramLoginBotUsername: "preview_bot",
    telegramLoginBotId: 1234567890,
    telegramOAuthClientId: 1234567890,
    telegramOAuthRequestAccess: ["write"],
    appVersion: "dev+local",
    appRepositoryUrl: "https://minishop.minidoc.cc/",
    themesCatalog: {
      default_theme: "dark",
      themes: [DEFAULT_DARK_THEME, LEGACY_LIGHT_THEME, WINDOWS_95_THEME, ASCII_THEME],
    },
  },
  data: {
    ok: true,
    user: {
      id: 100200300,
      username: "username",
      email: "user@example.com",
      email_verified: true,
      password_auth_enabled: false,
      telegram_id: 100200300,
      telegram_linked: true,
      telegram_notifications_status: "enabled",
      telegram_notifications_enabled: true,
      telegram_notifications_need_prompt: false,
      telegram_notifications_start_link: "https://t.me/preview_bot?start=notifications",
      telegram_photo_url: "",
      first_name: "Preview",
      language_code: "ru",
      is_admin: true,
    },
    auth_demo: {
      enabled: false,
      email: "3252a8@proton.me",
      code: "123456",
      password: "demo-password",
      telegram_id: 7410865527,
      telegram_username: "u3252a8",
      telegram_first_name: "3252a8",
      telegram_last_name: "",
    },
    subscription: {
      active: true,
      status: "ACTIVE",
      remaining_text: "25 д. 8 ч.",
      end_date_text: "24.05.2026",
      days_left: 25,
      config_link: "https://sub.example.com/sub/preview-token",
      connect_url: "https://sub.example.com/connect/preview-token",
      panel_short_uuid: "preview-token",
      install_share_token: "8f559061460e8fede78ef18dce887236",
      install_share_url: "https://app.example.com/s/8f559061460e8fede78ef18dce887236",
      traffic_used: "18.4 GB",
      traffic_limit: "100 GB",
      traffic_used_bytes: 19756849561,
      traffic_limit_bytes: 107374182400,
      premium_used: "32.0 GB",
      premium_limit: "50.0 GB",
      premium_used_bytes: 34359738368,
      premium_limit_bytes: 53687091200,
      premium_baseline_bytes: 53687091200,
      premium_topup_balance_bytes: 0,
      premium_is_limited: false,
      premium_title: "Premium-серверы",
      premium_node_labels: ["Premium NL-1", "Premium DE-1"],
      can_topup_regular_traffic: true,
      can_topup_premium_traffic: true,
      auto_renew_enabled: false,
      auto_renew_available: false,
      auto_renew_can_enable: false,
      auto_renew_provider_label: "CloudPayments",
      provider: "cloudpayments",
      max_devices: 5,
    },
    subscription_guides: {
      ok: true,
      enabled: true,
      config: INSTALL_GUIDES_CONFIG,
      source: "mock",
    },
    devices: {
      ok: true,
      enabled: true,
      current_devices: 3,
      max_devices: 5,
      max_devices_label: "5",
      devices: [
        {
          index: 1,
          display_name: "iPhone 15 Pro",
          platform_label: "iOS 18.4",
          user_agent: "Streisand/1.6 CFNetwork",
          created_at_text: "28.04.2026 16:12",
          hwid_short: "A1B2C3D4...98FA01",
          token: "preview-device-1",
          can_disconnect: true,
        },
        {
          index: 2,
          display_name: "MacBook Air",
          platform_label: "macOS 15.4",
          user_agent: "Happ/3.1.0",
          created_at_text: "29.04.2026 09:40",
          hwid_short: "F0E1D2C3...44AB22",
          token: "preview-device-2",
          can_disconnect: true,
        },
        {
          index: 3,
          display_name: "Android Phone",
          platform_label: "Android 15",
          user_agent: "v2rayNG/1.9.35",
          created_at_text: "30.04.2026 07:55",
          hwid_short: "778899AA...BCDD10",
          token: "preview-device-3",
          can_disconnect: true,
        },
      ],
    },
    plans: [
      { months: 1, price: 290, currency: "RUB", title: "1 месяц" },
      { months: 3, price: 790, currency: "RUB", title: "3 месяца" },
      { months: 6, price: 1490, currency: "RUB", title: "6 месяцев" },
      { months: 12, price: 2690, currency: "RUB", title: "12 месяцев" },
    ],
    payment_methods: [
      { id: "cloudpayments", name: "CloudPayments", icon: "CreditCard" },
      { id: "yookassa", name: "Карта", icon: "CreditCard" },
      { id: "platega_sbp", name: "Telegram Pay", icon: "CreditCard" },
      { id: "cryptopay", name: "Криптовалюта", icon: "Bitcoin" },
      { id: "freekassa", name: "Другие способы", icon: "Smartphone" },
    ],
    referral: {
      code: "ABCD1234",
      bot_link: "https://t.me/preview_bot?start=ref_uABCD1234",
      webapp_link: "https://minishop.app/ref/ABCD1234",
      invited_count: 4,
      purchased_count: 2,
      welcome_bonus_days: 3,
      welcome_bonus_without_telegram_enabled: true,
      welcome_bonus_requires_telegram: false,
      welcome_bonus_block_reason: "",
      one_bonus_per_referee: false,
      bonus_details: [
        { months: 1, title: "1 месяц", inviter_days: 14, friend_days: 7 },
        { months: 3, title: "3 месяца", inviter_days: 21, friend_days: 14 },
        { months: 6, title: "6 месяцев", inviter_days: 31, friend_days: 21 },
        { months: 12, title: "12 месяцев", inviter_days: 62, friend_days: 31 },
      ],
    },
    themes_catalog: {
      default_theme: "dark",
      themes: [DEFAULT_DARK_THEME, LEGACY_LIGHT_THEME, WINDOWS_95_THEME, ASCII_THEME],
    },
    settings: {
      support_url: "https://t.me/support",
      traffic_mode: false,
      my_devices_enabled: false,
      user_hwid_device_limit: 5,
      trial_enabled: true,
      trial_available: true,
      trial_without_telegram_enabled: true,
      trial_requires_telegram: false,
      trial_block_reason: "",
      trial_duration_days: 5,
      trial_traffic_limit_gb: 10,
      trial_traffic_strategy: "NO_RESET",
      subscription_purchase_description:
        "Покупая или продлевая подписку, вы получаете доступ к VPN/прокси-сервису, который помогает защищать ваше соединение и поддерживать стабильный доступ к сети.",
      subscription_guides_enabled: true,
      email_auth_enabled: true,
    },
  },
};
