"""Platega provider facade."""

from bot.payment_providers.platega.service import (
    ALL_METHODS_SPEC,
    CRYPTO_SPEC,
    INTERNATIONAL_SPEC,
    SBP_SPEC,
    SPECS,
    SUBSCRIPTION_SPEC,
    PlategaAllMethodsPresentation,
    PlategaConfig,
    PlategaCryptoPresentation,
    PlategaInternationalPresentation,
    PlategaSbpPresentation,
    PlategaService,
    PlategaSubscriptionPresentation,
    create_all_methods_webapp_payment,
    create_crypto_webapp_payment,
    create_international_webapp_payment,
    create_sbp_webapp_payment,
    create_service,
    create_subscription_webapp_payment,
    pay_platega_callback_handler,
    platega_webhook_route,
    reuse_webapp_payment,
    router,
)
from bot.payment_providers.platega.subscriptions import (
    SUBSCRIPTION_INTERVAL_BY_MONTHS,
    subscription_interval_for_months,
)

__all__ = [
    "ALL_METHODS_SPEC",
    "CRYPTO_SPEC",
    "INTERNATIONAL_SPEC",
    "SBP_SPEC",
    "SPECS",
    "SUBSCRIPTION_INTERVAL_BY_MONTHS",
    "SUBSCRIPTION_SPEC",
    "PlategaAllMethodsPresentation",
    "PlategaConfig",
    "PlategaCryptoPresentation",
    "PlategaInternationalPresentation",
    "PlategaSbpPresentation",
    "PlategaService",
    "PlategaSubscriptionPresentation",
    "create_all_methods_webapp_payment",
    "create_crypto_webapp_payment",
    "create_international_webapp_payment",
    "create_sbp_webapp_payment",
    "create_service",
    "create_subscription_webapp_payment",
    "pay_platega_callback_handler",
    "platega_webhook_route",
    "reuse_webapp_payment",
    "router",
    "subscription_interval_for_months",
]
